"""Initial migration with JSON fields and new models

Revision ID: 0c0d570bd30a
Revises: 
Create Date: 2026-02-20 10:40:49.904245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0d570bd30a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_id'), 'auth_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token'), 'auth_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_history_timestamp'), 'chat_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('medical_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('current_medications', sa.JSON(), nullable=True),
    sa.Column('family_history', sa.JSON(), nullable=True),
    sa.Column('surgical_history', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_medical_profiles_id'), 'medical_profiles', ['id'], unique=False)
    op.create_table('xray_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xray_reports_id'), 'xray_reports', ['id'], unique=False)
    op.create_index(op.f('ix_xray_reports_timestamp'), 'xray_reports', ['timestamp'], unique=False)
    op.create_index(op.f('ix_xray_reports_user_id'), 'xray_reports', ['user_id'], unique=False)
    op.alter_column('lab_reports', 'abnormal_values',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_lab_reports_timestamp'), 'lab_reports', ['timestamp'], unique=False)
    op.create_index(op.f('ix_lab_reports_user_id'), 'lab_reports', ['user_id'], unique=False)
    op.drop_constraint(None, 'lab_reports', type_='foreignkey')
    op.create_foreign_key(None, 'lab_reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_medication_logs_timestamp'), 'medication_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_medication_logs_user_id'), 'medication_logs', ['user_id'], unique=False)
    op.drop_constraint(None, 'medication_logs', type_='foreignkey')
    op.create_foreign_key(None, 'medication_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_nutrition_logs_timestamp'), 'nutrition_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.drop_constraint(None, 'nutrition_logs', type_='foreignkey')
    op.create_foreign_key(None, 'nutrition_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('symptom_logs', 'symptoms',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_symptom_logs_timestamp'), 'symptom_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'existing_conditions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'allergies',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'allergies',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'existing_conditions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_timestamp'), table_name='symptom_logs')
    op.alter_column('symptom_logs', 'symptoms',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'nutrition_logs', type_='foreignkey')
    op.create_foreign_key(None, 'nutrition_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_nutrition_logs_timestamp'), table_name='nutrition_logs')
    op.drop_constraint(None, 'medication_logs', type_='foreignkey')
    op.create_foreign_key(None, 'medication_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_medication_logs_user_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_timestamp'), table_name='medication_logs')
    op.drop_constraint(None, 'lab_reports', type_='foreignkey')
    op.create_foreign_key(None, 'lab_reports', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_lab_reports_user_id'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_timestamp'), table_name='lab_reports')
    op.alter_column('lab_reports', 'abnormal_values',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_xray_reports_user_id'), table_name='xray_reports')
    op.drop_index(op.f('ix_xray_reports_timestamp'), table_name='xray_reports')
    op.drop_index(op.f('ix_xray_reports_id'), table_name='xray_reports')
    op.drop_table('xray_reports')
    op.drop_index(op.f('ix_medical_profiles_id'), table_name='medical_profiles')
    op.drop_table('medical_profiles')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_timestamp'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
